server:
  port: 8200
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  servlet:
    context-path: /
    session:
      timeout: PT1H

mybatis-flex:
  datasource:
    ds1:
      url: jdbc:postgresql://localhost:5432/test_01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true&connectTimeout=60&socketTimeout=60
      username: postgres
      password: 123456
      type: hikari
      min-idle: 10
      max-pool-size: 30
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 800
